/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a-numadate' at '15/10/22 10:14' with Gradle 2.6
 *
 * @author a-numadate, @date 15/10/22 10:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
